apiVersion: v1
kind: Service
metadata:
 name: mysql-external
 labels:
  app: myapp
  tier: data
spec:
 type: NodePort
 ports:
  - port: 3306
    name: mysql-ext
    targetPort: 3306
    protocol: TCP
 selector:
  app: myapp
  
