apiVersion: v1
kind: Pod
metadata:
 name: mysql
 labels:
  app: myapp
  tier: data
spec:
 containers:
  - name: mysql
    image: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
    ports:
    - containerPort: 3306

